export type Lang = "EN" | "ZH";

const AMOUNT_DUE_ZH: Record<string, string> = { USD: "美元", CNY: "元", HKD: "港币", EUR: "欧元", SGD: "新加坡元" };

export const LABELS = {
  EN: {
    billedTo: "Billed To",
    amountDue: (c: string) => `Amount Due (${c})`,
    invoiceNumber: "Invoice Number",
    reference: "Reference",
    dateOfIssue: "Date of Issue",
    dueDate: "Due Date",
    description: "Description",
    rate: "Rate",
    qty: "Qty",
    lineTotal: "Line Total",
    subtotal: "Subtotal",
    tax: "Tax",
    total: "Total",
    amountPaid: "Amount Paid",
    terms: "Terms",
    paymentDetails: "Payment Details",
    currency: "Currency",
    accountName: "Account Name",
    accountNumber: "Account Number",
    bankName: "Bank Name",
    bankAddress: "Bank Address",
    bankCode: "Bank Code",
    branchCode: "Branch Code",
    swiftCode: "Swift Code",
    accountLocation: "Account Location",
    compactTitle: (label: string) => `${label} Details`,
    compactNumber: "Account number:",
    compactName: "Account name:",
  },
  ZH: {
    billedTo: "付款人",
    amountDue: (c: string) => `应付金额 (${AMOUNT_DUE_ZH[c] ?? c})`,
    invoiceNumber: "发票号码",
    reference: "参考",
    dateOfIssue: "出票日期",
    dueDate: "到期日",
    description: "描述",
    rate: "费用",
    qty: "量",
    lineTotal: "行合计",
    subtotal: "小计",
    tax: "税",
    total: "总计",
    amountPaid: "已付金额",
    terms: "条款",
    paymentDetails: "付款详情",
    currency: "币种",
    accountName: "帐户名称",
    accountNumber: "帐号",
    bankName: "银行名",
    bankAddress: "银行地址",
    bankCode: "银行代码",
    branchCode: "分行代码",
    swiftCode: "SWIFT代码",
    accountLocation: "帐户所在地",
    compactTitle: (label: string) => `${label} 付款详情`,
    compactNumber: "帐号：",
    compactName: "帐户名称：",
  },
} as const;
